#include "test-incl/test_compositor.hpp"
#include "test-incl/test_curry.hpp"
#include "test-incl/test_either.hpp"
#include "test-incl/test_maybe.hpp"
#include "test-incl/test_traits.hpp"
#include "test-incl/test_combinator.hpp"
